### ISSUE TITLE
Cannot find the parameter "no_op max" in the code 

### ISSUE THREAD

**Issue by boranzhao** [deepmind/dqn#4]
Hi guys, 

I noticed that there is a parameter named "no_op max" listed in the paper "Human-level control through deep reinforcement learning". In the paper, its meaning is "Maximum number of 'do nothing' actions to be performed". However, I could not find this parameter in the code. Could you explain why?

Another question, in training or testing, the game needs to be started by executing a specific action at the beginning of each episode. For example, for Breakout, "FIRE" (corresponding to action 1 in OpenAI gym) needs to be executed to start an episode. I was wondering whether the DQN agent do this on its own through learning, or this is encoded in the code by human. 

Thanks.

**Comment by GeorgOstrovski** [comment]
Hi, 

Regarding your first question, see my response to [your other question](https://github.com/deepmind/dqn/issues/3) - the parameter is called `random_starts`.

Regarding the starting action: Some of the Atari games in the Xitari fork of the ALE which we are using here apply a starting action (or several) themselves, see e.g. [here](https://github.com/deepmind/xitari/blob/master/games/supported/Surround.cpp#L120). Other games don't define this function and therefore don't automatically apply these actions - we didn't hard-code this into DQN either, so the agent would need to discover this itself.

Cheers.

**Comment by boranzhao** [comment]
@GeorgOstrovski  Hi, thanks for your reply. I have two more question. Firstly, why do some of the Atari games apply a starting action while others do not?  Secondly, I am currently testing Breakout. For this specific game,  will a starting action be applied first before the dqn agent starts learning and acting?

**Comment by GeorgOstrovski** [comment]
You can look this up in xitari for each game: The base class `RomSettings` [here](https://github.com/deepmind/xitari/blob/73c37a35f3a340f1a7ef95271cf4d823821253f7/games/RomSettings.cpp#L64) defines a method `getStartingActions()` which by default returns an empty action vector. Some games override this method, e.g. Asterix [here](https://github.com/deepmind/xitari/blob/73c37a35f3a340f1a7ef95271cf4d823821253f7/games/supported/Asterix.cpp#L130) and provide some list of actions to be executed at each episode beginning. If a game doesn't override it, there are no automatically executed actions. Breakout ([here](https://github.com/deepmind/xitari/blob/73c37a35f3a340f1a7ef95271cf4d823821253f7/games/supported/Breakout.cpp)) doesn't override the method, i.e. there are no automatically executed actions.
