### ISSUE TITLE
[Question] Does the momentum config value match the Nature paper?

### ISSUE THREAD

**Issue by tlwillke** [deepmind/dqn#5]
Thanks for sharing your code.  Very helpful!

In Minh et al. (2015), Extended Data Table 1 lists the momentum as 0.95. 
 However, in this code the value seems to be set to 0.0:
[self.deltas:mul(0):addcdiv(self.lr, self.dw, self.tmp)](https://github.com/deepmind/dqn/blob/master/dqn/NeuralQLearner.lua#L276)

Am I interpreting your code correctly?  Is there a mismatch?

Thanks in advance!

--Ted

**Comment by GeorgOstrovski** [comment]
I believe the momentum and squared gradient momentum values of 0.95, as given in the paper, refer to the respective gradient / squared gradient decay factors in the RMSProp algorithm, they are being correctly applied a few lines above the one you are referencing: [here](http://go/gh/deepmind/dqn/blob/master/dqn/NeuralQLearner.lua#L276) and [here](http://go/gh/deepmind/dqn/blob/master/dqn/NeuralQLearner.lua#L268).

**Comment by tlwillke** [comment]
Hi @GeorgOstrovski, I can't view the 'here' and 'here' links above because they seem to link to a privileged location.  I believe you are referring to [here](https://github.com/deepmind/dqn/blob/master/dqn/NeuralQLearner.lua#L266) and [here](https://github.com/deepmind/dqn/blob/master/dqn/NeuralQLearner.lua#L268), correct?

**Comment by GeorgOstrovski** [comment]
Yes you are right, sorry about the broken links!
